FROM alpine:latest
LABEL org.opencontainers.image.source="https://github.com/redraven2459/lighthouse"

WORKDIR /srv/lighthouse_server
RUN apk add --no-cache python3 py3-pip git
COPY pyproject.toml .
COPY alembic.ini ./alembic.ini
COPY alembic ./alembic
COPY src ./src
RUN python -m pip install --no-cache-dir --break-system-packages .

COPY docker/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

WORKDIR /srv
RUN git clone https://github.com/redraven2459/tidekeeper.git
WORKDIR /srv/tidekeeper/TIDALDL-PY
RUN python -m pip install --no-cache-dir --break-system-packages -e .

WORKDIR /srv/InitialData/Tidekeeper
COPY docker/.tidal-dl.json.example ./.tidal-dl.json

WORKDIR /srv/lighthouse_server
EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["python", "-m", "uvicorn", "main:app" "--app-dir", "src/lighthouse_server/__main__.py", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
