FROM ubuntu AS build

RUN apt-get update
RUN apt-get install -y curl git unzip
RUN git clone https://github.com/flutter/flutter.git
ENV PATH="/flutter/bin:${PATH}"

COPY src/lighthouse_client /app
WORKDIR /app
RUN flutter clean
RUN flutter pub get
RUN flutter build web

FROM nginx:alpine
LABEL org.opencontainers.image.source="https://github.com/redraven2459/lighthouse"
COPY --from=build /app/build/web /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
